/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as ProductsImport } from "./pages/products"
import { Route as OrdersImport } from "./pages/orders"
import { Route as HomeImport } from "./pages/home"
import { Route as CustomersImport } from "./pages/customers"
import { Route as IndexImport } from "./pages/index"
import { Route as ProfileIndexImport } from "./pages/profile/index"
import { Route as AuthRegisterImport } from "./pages/auth/register"
import { Route as AuthLoginImport } from "./pages/auth/Login"

// Create/Update Routes

const ProductsRoute = ProductsImport.update({
  path: "/products",
  getParentRoute: () => rootRoute,
} as any)

const OrdersRoute = OrdersImport.update({
  path: "/orders",
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: "/home",
  getParentRoute: () => rootRoute,
} as any)

const CustomersRoute = CustomersImport.update({
  path: "/customers",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: "/profile/",
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: "/auth/register",
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: "/auth/Login",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/customers": {
      preLoaderRoute: typeof CustomersImport
      parentRoute: typeof rootRoute
    }
    "/home": {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    "/orders": {
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    "/products": {
      preLoaderRoute: typeof ProductsImport
      parentRoute: typeof rootRoute
    }
    "/auth/Login": {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    "/auth/register": {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    "/profile/": {
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CustomersRoute,
  HomeRoute,
  OrdersRoute,
  ProductsRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  ProfileIndexRoute,
])

/* prettier-ignore-end */
