/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as OrdersImport } from "./pages/Orders"
import { Route as HomeImport } from "./pages/Home"
import { Route as CustomersImport } from "./pages/Customers"
import { Route as IndexImport } from "./pages/index"
import { Route as ProfileIndexImport } from "./pages/profile/index"
import { Route as AuthRegisterImport } from "./pages/auth/Register"
import { Route as AuthLoginImport } from "./pages/auth/Login"

// Create/Update Routes

const OrdersRoute = OrdersImport.update({
  path: "/Orders",
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: "/Home",
  getParentRoute: () => rootRoute,
} as any)

const CustomersRoute = CustomersImport.update({
  path: "/Customers",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: "/profile/",
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: "/auth/Register",
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: "/auth/Login",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/Customers": {
      preLoaderRoute: typeof CustomersImport
      parentRoute: typeof rootRoute
    }
    "/Home": {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    "/Orders": {
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    "/auth/Login": {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    "/auth/Register": {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    "/profile/": {
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CustomersRoute,
  HomeRoute,
  OrdersRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  ProfileIndexRoute,
])

/* prettier-ignore-end */
